language: node_js
node_js:
  - 0.11

branches:
  only:
    - master

before_script:
  - npm install
  - npm run build

script:
  - npm test

after_success:
  - openssl aes-256-cbc -K $encrypted_2bc4d1d38456_key -iv $encrypted_2bc4d1d38456_iv -in id_ecdsa.enc -out ~/.ssh/id_ecdsa -d
  - chmod 600 ~/.ssh/id_ecdsa
  - bash ./bin/deploy.sh
